/**
 * @file    oled_config.h
 * @brief   OLED显示驱动配置文件
 * @author  Generated by AI Assistant
 * @date    2024
 */

#ifndef __OLED_CONFIG_H
#define __OLED_CONFIG_H

/* 包含必要的头文件 */
#include "main.h"
#include "spi.h"
/* ================================= 硬件配置 ================================= */

/* SPI配置 */
#define OLED_SPI_HANDLE hspi1          // SPI句柄
#define OLED_SPI_TIMEOUT HAL_MAX_DELAY // SPI超时时间

/* GPIO配置 */
#define OLED_RES_PIN GPIO_PIN_0 // 复位引脚
#define OLED_RES_PORT GPIOB     // 复位端口
#define OLED_DC_PIN GPIO_PIN_1  // 数据/命令选择引脚
#define OLED_DC_PORT GPIOB      // 数据/命令选择端口

/* 可选的CS引脚配置（如果使用软件控制CS） */
#define OLED_USE_CS_PIN 0 // 是否使用CS引脚控制
#if OLED_USE_CS_PIN
#define OLED_CS_PIN GPIO_PIN_4 // CS引脚
#define OLED_CS_PORT GPIOA     // CS端口
#define OLED_CS_Set() HAL_GPIO_WritePin(OLED_CS_PORT, OLED_CS_PIN, GPIO_PIN_SET)
#define OLED_CS_Clr() HAL_GPIO_WritePin(OLED_CS_PORT, OLED_CS_PIN, GPIO_PIN_RESET)
#endif

/* ================================= 显示配置 ================================= */

/* 显示屏分辨率 */
#define OLED_WIDTH 128 // 显示宽度
#define OLED_HEIGHT 64 // 显示高度
#define OLED_PAGES 8   // 页数 (HEIGHT/8)

/* 字体配置 */
#define OLED_FONT_6X8_ENABLE 1  // 启用6x8字体
#define OLED_FONT_8X16_ENABLE 1 // 启用8x16字体

/* 中文字体配置 */
#define OLED_CHINESE_ENABLE 1 // 启用中文显示
#define OLED_CHINESE_16X16 1  // 启用16x16中文字体

/* 图形功能配置 */
#define OLED_BITMAP_ENABLE 1   // 启用位图显示
#define OLED_GRAPHICS_ENABLE 0 // 启用图形绘制功能（线条、矩形等）

/* ================================= 功能配置 ================================= */

/* 显示效果配置 */
#define OLED_REVERSE_ENABLE 1 // 启用反色显示功能
#define OLED_ROTATE_ENABLE 1  // 启用旋转显示功能
#define OLED_FADE_ENABLE 0    // 启用淡入淡出效果

/* 性能配置 */
#define OLED_USE_DMA 0       // 使用DMA传输（需要配置DMA）
#define OLED_BUFFER_ENABLE 0 // 启用显示缓冲区

/* 调试配置 */
#define OLED_DEBUG_ENABLE 0 // 启用调试功能
#define OLED_TEST_ENABLE 1  // 启用测试功能

/* ================================= 高级配置 ================================= */

/* SSD1306 初始化参数配置 */
#define OLED_CONTRAST_VALUE 0xCF     // 对比度设置 (0x00-0xFF)
#define OLED_DISPLAY_OFFSET 0x00     // 显示偏移
#define OLED_DISPLAY_START_LINE 0x40 // 显示起始行
#define OLED_SEGMENT_REMAP 0xA1      // 段重映射 (0xA0/0xA1)
#define OLED_COM_SCAN_DIR 0xC8       // COM扫描方向 (0xC0/0xC8)
#define OLED_COM_PIN_CONFIG 0x12     // COM引脚配置
#define OLED_VCOM_DETECT 0x40        // VCOM检测级别

/* 时钟配置 */
#define OLED_CLOCK_DIVIDE 0x80     // 时钟分频
#define OLED_PRECHARGE_PERIOD 0xF1 // 预充电周期
#define OLED_MEMORY_MODE 0x02      // 内存寻址模式

/* ================================= 兼容性配置 =============================== */

/* 兼容不同的OLED型号 */
#define OLED_TYPE_SSD1306 1 // SSD1306控制器
#define OLED_TYPE_SSD1315 0 // SSD1315控制器
#define OLED_TYPE_SH1106 0  // SH1106控制器

/* 兼容不同的显示尺寸 */
#define OLED_SIZE_128X64 1 // 128x64分辨率
#define OLED_SIZE_128X32 0 // 128x32分辨率
#define OLED_SIZE_96X16 0  // 96x16分辨率

/* ================================= 错误检查 ================================= */

/* 检查SPI句柄是否定义 */
#ifndef OLED_SPI_HANDLE
#error "OLED_SPI_HANDLE not defined! Please define it in oled_config.h"
#endif

/* 检查GPIO配置 */
#if !defined(OLED_RES_PIN) || !defined(OLED_RES_PORT)
#error "OLED RES pin not configured! Please define OLED_RES_PIN and OLED_RES_PORT"
#endif

#if !defined(OLED_DC_PIN) || !defined(OLED_DC_PORT)
#error "OLED DC pin not configured! Please define OLED_DC_PIN and OLED_DC_PORT"
#endif

/* 检查分辨率配置 */
#if OLED_WIDTH != 128
#error "Currently only 128 pixel width is supported"
#endif

#if OLED_HEIGHT != 64 && OLED_HEIGHT != 32
#error "Currently only 64 and 32 pixel heights are supported"
#endif

/* ================================= 宏定义 ================================= */

/* 外部变量声明 */
extern SPI_HandleTypeDef OLED_SPI_HANDLE;

/* GPIO控制宏 */
#define OLED_RES_Set() HAL_GPIO_WritePin(OLED_RES_PORT, OLED_RES_PIN, GPIO_PIN_SET)
#define OLED_RES_Clr() HAL_GPIO_WritePin(OLED_RES_PORT, OLED_RES_PIN, GPIO_PIN_RESET)
#define OLED_DC_Set() HAL_GPIO_WritePin(OLED_DC_PORT, OLED_DC_PIN, GPIO_PIN_SET)
#define OLED_DC_Clr() HAL_GPIO_WritePin(OLED_DC_PORT, OLED_DC_PIN, GPIO_PIN_RESET)

/* 调试宏 */
#if OLED_DEBUG_ENABLE
#define OLED_DEBUG(fmt, ...) printf("OLED: " fmt "\r\n", ##__VA_ARGS__)
#else
#define OLED_DEBUG(fmt, ...)
#endif

/* 条件编译宏 */
#if OLED_CHINESE_ENABLE
#define CHINESE_FONT_ENABLED
#endif

#if OLED_BUFFER_ENABLE
#define OLED_BUFFER_SIZE (OLED_WIDTH * OLED_HEIGHT / 8)
extern uint8_t oled_buffer[OLED_BUFFER_SIZE];
#endif

#endif /* __OLED_CONFIG_H */
